stages: 
  - build-maven
  - build-image
  - parsian

build-maven:
  image: $repository/docker/jdk8-mvn:latest
  stage: build-maven
  tags: 
    - loan-maven 
  script:
    - mvn install:install-file -Dfile=/root/ojdbc6-11.2.0.4.jar -DgroupId=com.oracle -DartifactId=ojdbc6 -Dversion=11.2.0.4 -Dpackaging=jar
    - mvn clean compile package -Dmaven.test.skip=true 
    - ls 
    - slepp 60
  artifacts:
    paths:
     - mobile-bank-service/target/*.war
  only:
    changes:
      - src/**/*.*
      - Dockerfile 
      - pom.xml 
    refs:
      - docker

build-image-Development: 
  dependencies: 
    - build-maven 
  stage: build-image
  tags:
    - loan-build
  script:
    - sed -i 's/\#DEVELOP//g' Dockerfile
    - docker login -u $user_repository -p $pass_repository https://$repository
    - docker build -t $CONTAINER_NAME .
    - docker tag $CONTAINER_NAME  $repository/docker/loan/$CONTAINER_NAME:TestStage
    - docker push $repository/docker/loan/$CONTAINER_NAME:TestStage
    - docker logout
  only:
    changes:
      - src/**/*.*
      - Dockerfile 
      - pom.xml
    refs:
      - docker
  when: manual 

Development:
  stage: parsian
  tags:
    - prep
  script:
    - docker login -u $user_repository -p $pass_repository https://$repository
    - (if [ "$(docker rmi -f $repository/docker/loan/$CONTAINER_NAME:TestStage-old)" ]; then echo "Image removed"; else echo OK; fi;);
    - (if [ "$(docker tag $repository/docker/loan/$CONTAINER_NAME:TestStage $repository/docker/loan/$CONTAINER_NAME:TestStage-old)" ]; then echo "taged image"; else echo OK; fi;)
    - docker pull $repository/docker/loan/$CONTAINER_NAME:TestStage
    - sed -i 's/DOCKERIMAGE/TestStage/g' docker-compose.yml
    - sed -i 's/\#DEVELOP//g' docker-compose.yml
    - docker-compose up -d --force-recreate
    #- docker run  -d  --name gateway-service --env-file .env/db.env  --network loan-net -p 8080:8080  -l  collect_logs_with_filebeat=true -l decode_log_event_to_json_object=true $repository/docker/loan/gateway-service:TestStage1 
    - sleep 60
    - (if [  "$(docker ps -aq -f name=$CONTAINER_NAME)" ];  then echo " Job Succeed"; else exit 5; fi;);
  when : manual
  only:
    - docker


