CREATE TABLE TRANSACTION
(
    ID                       NUMBER(16) PRIMARY KEY NOT NULL,
    MOBILE_NUMBER            VARCHAR(20)            NOT NULL,
    CIF                      VARCHAR(100)           NULL,
    SOURCE_TYPE              NUMBER(2)              NULL,
    SOURCE                   VARCHAR(100)           NULL,
    AMOUNT                   NUMBER(16)             NULL,
    TRANSACTION_TYPE         NUMBER(2)              NOT NULL,
    RESPONSE_CODE            VARCHAR(10)            NULL,
    STATUS                   NUMBER(2)              NULL,
    TRANSACTION_DATE         TIMESTAMP(6)           NULL,
    CREATED_DATE             TIMESTAMP(6)           NOT NULL,
    MODIFIED_DATE            TIMESTAMP(6)           NOT NULL,
    CLIENT_IP                VARCHAR(50)            NOT NULL,
    FAIL_REASON              VARCHAR2(1000)         NULL,
    DISPLAY_MESSAGE          VARCHAR2(1000)         NULL,
    ORIGINAL_FAIL_REASON     VARCHAR2(1000)         NULL,
    ORIGINAL_DISPLAY_MESSAGE VARCHAR2(1000)         NULL
);

CREATE TABLE CARD_TRANSFER
(
    TRANSACTION_ID   NUMBER(16) PRIMARY KEY NOT NULL,
    DESTINATION      VARCHAR(50)            NOT NULL,
    DESTINATION_TYPE NUMBER(2)              NOT NULL,
    CONSTRAINT FK_CARD_TRANSFER__TRANSACTION FOREIGN KEY (TRANSACTION_ID) REFERENCES TRANSACTION (ID)
);

CREATE TABLE CHARGE
(
    TRANSACTION_ID     NUMBER(16) PRIMARY KEY NOT NULL,
    REQUEST_ID         VARCHAR(100)           NULL,
    PRODUCT_ID         NUMBER(16)             NOT NULL,
    DESTINATION_MOBILE VARCHAR(20)            NOT NULL,
    CHARGE_STATUS      NUMBER(2)              NOT NULL,
    RESERVE_STATUS     NUMBER(2)              NULL,
    REVERSE_STATUS     NUMBER(2)              NULL,
    PAYMENT_STATUS     NUMBER(2)              NULL,
    REFUNDED           NUMBER(1)              NULL,
    CONSTRAINT FK_CHARGE__TRANSACTION FOREIGN KEY (TRANSACTION_ID) REFERENCES TRANSACTION (ID)
);

CREATE TABLE PAY_BILL
(
    TRANSACTION_ID NUMBER(16) PRIMARY KEY NOT NULL,
    BILL_ID        VARCHAR(100)           NOT NULL,
    PAY_ID         VARCHAR(100)           NOT NULL,
    BILL_TYPE      NUMBER(2)              NULL,
    CONSTRAINT FK_PAY_BILL__TRANSACTION FOREIGN KEY (TRANSACTION_ID) REFERENCES TRANSACTION (ID)
);