CREATE SEQUENCE TRANSACTION_SEQUENCE
    START WITH 1000
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE TRANSACTION_LOG_SEQUENCE
    START WITH 1000
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;