CREATE TABLE CUSTOMER
(
    MOBILE_NUMBER VARCHAR(20) PRIMARY KEY NOT NULL,
    CIF           VARCHAR(100)            NOT NULL,
    NAME          VARCHAR2(200 CHAR)      NULL,
    GENDER        VARCHAR2(50 CHAR)       NULL,
    CREATED_DATE  TIMESTAMP(6)            NOT NULL,
    MODIFIED_DATE TIMESTAMP(6)            NOT NULL
);

CREATE INDEX CIF_IDX ON CUSTOMER (CIF);